
name: Test with pytest

on:
  push:
    branches: [ "main", "test-workflows" ]
  pull_request:
    branches: [ "main", "test-workflows"  ]

permissions:
  contents: read

jobs:
  test:
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install .[test]
        pip install .
    - name: Test with pytest
      run: |
        python -m pytest
